### ISSUE TITLE
Blog CSS

### ISSUE THREAD

**Issue by dragice** [transparentstats/transparentstats-website#2]
Title, Header 1 and Header 2 currently have the same font size.

**Comment by mjskay** [comment]
Yeah, that was a deliberate choice: I use header 1 and title interchangeably (which the template also does internally: it just applies a different class to the h1 tag to make an article title). Thus, in terms of the structure of the page, h1 should not be used for anything except the article title (otherwise you would have top-level headings that, in terms of page structure, appear to be at the same level as the article title).

Given that, h1 should only appear once in any article: as its title. The template default had h1 being huge, so I bumped it down in size. Because it only appears once, h1 is still mostly distinct from other headings, so I felt this was an okay compromise (though I could revert this, or we could make h2 a little smaller, which might be a better choice).

The upshot is that headings within an article should start at h2 and not h1 (i.e. `## blah blah blah` instead of `#blah blah blah`).

**Comment by mjskay** [comment]
I will make h2 a bit smaller
